<?php

/**
 * @file
 * This is the main module file for Petitions Profanity Filters.
 */

/**
 * Implements hook_menu().
 */
function petitions_profanity_filters_menu() {
  $items = array();

  // Provide an administration page for configuring homepage content.
  $items['admin/config/petitions/profanity'] = array(
    'title' => 'Profanity Filters',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('petitions_profanity_filters_configure'),
    'access arguments' => array('administer site configuration'),
    'file' => 'petitions_profanity_filters.admin.inc',
    'description' => "Configure profanity filters.",
  );

  return $items;
}
